// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWU_dhJSIyZXLjXBKEclW-9jt1IXZm7wg',
    appId: '1:362774588704:web:5063e53ca6615b48303b45',
    messagingSenderId: '362774588704',
    projectId: 'm3nko-3c577',
    authDomain: 'm3nko-3c577.firebaseapp.com',
    storageBucket: 'm3nko-3c577.appspot.com',
    measurementId: 'G-4LC4GNSJL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjhqblF-bfiao8b7cBavAvAFrli4IdxrI',
    appId: '1:362774588704:android:f45a12175cc23e5c303b45',
    messagingSenderId: '362774588704',
    projectId: 'm3nko-3c577',
    storageBucket: 'm3nko-3c577.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1ZrAxL3Q_xMdxCYNuH-KYiLcSbzdldqI',
    appId: '1:362774588704:ios:368d205661d9d17e303b45',
    messagingSenderId: '362774588704',
    projectId: 'm3nko-3c577',
    storageBucket: 'm3nko-3c577.appspot.com',
    iosBundleId: 'com.example.m3ngon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1ZrAxL3Q_xMdxCYNuH-KYiLcSbzdldqI',
    appId: '1:362774588704:ios:0b573e7930ddf8bf303b45',
    messagingSenderId: '362774588704',
    projectId: 'm3nko-3c577',
    storageBucket: 'm3nko-3c577.appspot.com',
    iosBundleId: 'com.example.m3ngon.RunnerTests',
  );
}
